"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { authService } from "@/services/auth/auth.service";
import type { RegistrationData } from "@/types/auth";

const initial: RegistrationData = { businessName: "", ownerName: "", mobile: "", email: "", password: "", confirmPassword: "", drugLicenseNumber: "", gstNumber: "", address: "", city: "", state: "", pincode: "", role: "retailer" };
export default function SignupPage() {
  const [form, setForm] = useState(initial); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  function update(name: keyof RegistrationData, value: string) { setForm(current => ({ ...current, [name]: value })); setError(""); setMessage(""); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setMessage(""); if (form.password !== form.confirmPassword) { setError("Passwords do not match."); return; } setSaving(true); const result = await authService.register(form); setSaving(false); if (result.ok) setMessage(result.message ?? "Registration successful."); else setError(result.message ?? "Registration failed."); }
  return <main className="login-wrap"><section className="card login-box" style={{ maxWidth: 760 }}><div className="login-logo"><i className="bi bi-capsule-pill me-2" />MediStores</div><h1 className="h4 mt-4">Dealer / Retailer Registration</h1>{error && <div className="alert alert-danger">{error}</div>}{message && <div className="alert alert-success">{message}</div>}<form onSubmit={submit} className="row g-3">{(["businessName", "ownerName", "mobile", "email", "drugLicenseNumber", "gstNumber", "address", "city", "state", "pincode"] as const).map(name => <div className={name === "address" ? "col-12" : "col-md-6"} key={name}><label className="form-label" htmlFor={name}>{name}</label><input id={name} className="form-control" value={form[name]} onChange={event => update(name, event.target.value)} required /></div>)}<div className="col-md-6"><label className="form-label" htmlFor="password">Password</label><input id="password" className="form-control" type="password" value={form.password} onChange={event => update("password", event.target.value)} required /></div><div className="col-md-6"><label className="form-label" htmlFor="confirmPassword">Confirm password</label><input id="confirmPassword" className="form-control" type="password" value={form.confirmPassword} onChange={event => update("confirmPassword", event.target.value)} required /></div><div className="col-md-6"><label className="form-label" htmlFor="role">Role</label><select id="role" className="form-select" value={form.role} onChange={event => update("role", event.target.value as RegistrationData["role"])}><option value="retailer">Retailer</option><option value="dealer">Dealer</option></select></div><div className="col-12"><button className="btn btn-brand w-100" disabled={saving}>{saving ? "Creating account..." : "Create account"}</button></div></form><Link href="/login" className="d-block text-center mt-3 text-primary small">Already registered? Sign in</Link></section></main>;
}
